project:
  type: website
  output-dir: docs

website:
  title: "Morgan Gregory"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - project.qmd
      - CombiningDataFrames.qmd
      
    
    tools:
      - icon: linkedin
        href: https://www.linkedin.com/
      - icon: github
        menu:
          - text: Source Code
            href: https://github.com
          - text: Report a Bug
            href: https://github.com  

format:
  html:
    theme: lux  # flatly, litera, lumen, lux, minty, pulse, sandstone, zephyr, quartz, yeti, cosmo, sketchy
    css: styles.css
    toc: true

execute: 
  freeze: auto

